# Generated by Django 5.2.8 on 2025-11-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('image_name', models.CharField(max_length=255)),
                ('image_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bone_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fracture_detected', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('risk_factors', models.JSONField(blank=True, null=True)),
                ('treatment_plan', models.JSONField(blank=True, null=True)),
                ('timeline', models.JSONField(blank=True, null=True)),
                ('report_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
