# Generated by Django 6.0.2 on 2026-02-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='accuracy',
            field=models.FloatField(default=92.4),
        ),
    ]
